version: "3"
services:
  app:
    networks:
      - mynetwork

  visualizer:
    image: alexellis2/visualizer-arm:latest
    container_name: visualizer
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - mynetwork

  # redis:
  #   image: arm32v6/redis:5-alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - /home/docker/data:/data
  #   deploy:
  #     placement:
  #         constraints: [node.role == manager]
  #   command: redis-server --appendonly yes
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
