version: "3"
services:
  app:
    build: .
    container_name: dev.docker_demo
    image: docker_demo:dev
    command: "npm run inspect"
    ports:
      - "9229:9229"
    volumes:
      - ./src:/home/node/app/src
