version: "3"
services:
  app:
    image: ${DOCKER_USER}/docker_demo:latest
    container_name: prod.api.docker_demo
    command: "npm start"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:3001"
