version: "3.7"
services:
  app:
    init: true
    image: ${DOCKER_USER}/docker_demo:${TAG}
    container_name: prod.docker_demo
    command: "npm start"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - 8000:${PORT}
