version: "3"
services:
  app:
    image: ${DOCKER_USER}/docker_demo:latest
    command: "npm start"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:3001"
